# Generated by Django 4.2.3 on 2023-07-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UPIAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upi_id", models.CharField(max_length=250)),
                ("spam_mark", models.IntegerField()),
                ("ham_mark", models.IntegerField()),
            ],
        ),
    ]
