# Generated by Django 4.2.3 on 2023-08-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="carrier",
            field=models.CharField(default="vodafone", max_length=200),
            preserve_default=False,
        ),
    ]
