# Generated by Django 4.2.3 on 2023-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0002_phonenumber_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="phone_region",
            field=models.CharField(default="India", max_length=250),
            preserve_default=False,
        ),
    ]
