# Generated by Django 3.2.7 on 2023-08-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_phonenumber_phone_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='ham_mark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
